# sphere-stack resources
#
# This is all the microservices which combine to make the sphere cloud resource services.
#
# NOTE: You will want to reconfigure all the passwords in here and the test_sql.sql file.
# 

# douitsu, activation databases
spheremysql:
  privileged: true
  image: tutum/mysql
  ports:
    - "3306:3306"
  volumes:
    - /var/lib/sphere-stack/mysql:/var/lib/mysql
  environment:
    - MYSQL_USER="ninja"
    - MYSQL_PASS="ninja"
  expose:
    - "3306"

# document store
spherecouch:
  image: klaemo/couchdb
  ports:
    - "5984:5984"
  volumes:
    - /var/lib/sphere-stack/couchdb:/usr/local/var/lib/couchdb
  expose:
    - "5984"

# message broker
sphererabbit:
  hostname: sphererabbit
  image: ninjablocks/rabbitmq
  environment:
    - RABBITMQ_PASS=ofjoHyibkaibHiammagsenun
  volumes:
    - /var/lib/sphere-stack/rabbitmq:/var/lib/rabbitmq
  ports:
    - "1883:1883"
    - "5672:5672"
    - "15672:15672"
  expose:
    - "1883"
    - "5672"
    - "15672"

# cache
sphereredis:
  image: redis
  ports:
    - "6379:6379"
  expose:
    - "6379"