# sphere-stack services
#
# This is all the microservices which combine to make the sphere cloud.
#
# NOTE: You will want to reconfigure all the passwords in here and the test_sql.sql file.
# 

# identity provider
douitsu:
  image: ninjasphere/douitsu:6b1d73e
  environment:
    - DEBUG=*
    - CACHE_URL=redis://redis
    - DB_URL=mysql://douitsu:douitsu@mysql:3306/douitsu
    - NODE_ENV=production
  external_links:
    - spherestack_sphereredis_1:redis
    - spherestack_spheremysql_1:mysql
  ports:
    - "3333:3333"
  expose:
    - "3333"

# sphere activation service
activation:
  image: ninjasphere/sphere-activation-service:90c74a0
  environment:
    - DEBUG=*
    - USVC_CONFIG_ENV=docker
    - NODE_ENV=development
    - usvc_rpcService_signing_secret=NefofvigdadEjlien8Schyk8
    - usvc_amqp_url=amqp://admin:ofjoHyibkaibHiammagsenun@rabbit:5672
  external_links:
    - spherestack_sphereredis_1:redis
    - spherestack_spheremysql_1:mysql
    - spherestack_sphererabbit_1:rabbit
  ports:
    - "5100:5100"
  expose:
    - "5100"

# sphere rest api service
apiservice:
  image: ninjasphere/sphere-api-service:a13fb9f
  environment:
    - DEBUG=*
    - USVC_CONFIG_ENV=docker
    - NODE_ENV=development
    - usvc_amqp_url=amqp://admin:ofjoHyibkaibHiammagsenun@rabbit:5672
    - usvc_rpcService_signing_secret=NefofvigdadEjlien8Schyk8
    - usvc_activationService_signing_secret=NefofvigdadEjlien8Schyk8
    - usvc_modelStoreService_signing_secret=NefofvigdadEjlien8Schyk8
    - usvc_sessions_secret=OjIakHisvaykafmoafOabFey
    - usvc_oauth_callbackURL=https://apiservice.example.com/auth/ninja/callback
    - usvc_oauth_authorizationURL=https://douitsu.example.com/dialog/authorize
    - usvc_oauth_clientID=app_XX
    - usvc_oauth_clientSecret=sk_XX
    - usvc_sessions_secret=EcBetvabdigobejBararuch2
  links:
    - activation:activation
    - douitsu:douitsu
    - modelservice:modelservice
  external_links:
    - spherestack_sphereredis_1:redis
    - spherestack_spheremysql_1:mysql
    - spherestack_sphererabbit_1:rabbit
  ports:
    - "5200:5200"
  expose:
    - "5200"

# sphere rpc service
rpcservice:
  image: ninjasphere/sphere-rpc-service:e4de51c
  links:
    - modelservice:modelservice
  environment:
    - DEBUG=*
    - USVC_CONFIG_ENV=docker
    - NODE_ENV=development
    - usvc_amqp_url=amqp://admin:ofjoHyibkaibHiammagsenun@rabbit:5672
    - usvc_modelStoreService_signing_secret=NefofvigdadEjlien8Schyk8
  external_links:
    - spherestack_sphereredis_1:redis
    - spherestack_spheremysql_1:mysql
    - spherestack_sphererabbit_1:rabbit
  ports:
    - "5900:5900"
  expose:
    - "5900"

# sphere model store service
modelservice:
  image: ninjasphere/sphere-modelstore-service:2463a5e
  environment:
    - DEBUG=*
    - USVC_CONFIG_ENV=docker
    - NODE_ENV=development
    - usvc_rpcService_signing_secret=NefofvigdadEjlien8Schyk8
  external_links:
    - spherestack_spherecouch_1:couchdb
  ports:
    - "5600:5600"
  expose:
    - "5600"

# sphere state service
stateservice:
  image: ninjasphere/sphere-state-service:2a2b68c
  environment:
    - DEBUG=true
    - REDIS_URL=redis://redis:6379
    - RABBIT_URL=amqp://admin:ofjoHyibkaibHiammagsenun@rabbit:5672
  external_links:
    - spherestack_sphereredis_1:redis
    - spherestack_sphererabbit_1:rabbit
  ports:
    - "6100:6100"
  expose:
    - "6100"

# sphere mqtt proxy
mqttproxy:
  image: ninjablocks/mqtt-proxy:e272ac0
  environment:
    - BACKEND_USER=admin
    - BACKEND_PASS=ofjoHyibkaibHiammagsenun
  external_links:
    - spherestack_spheremysql_1:mysql
    - spherestack_sphererabbit_1:rabbit
  ports:
    - "6300:6300"
  expose:
    - "6300"

# cache
spherehaproxy:
  image: ninjablocks/haproxy:95d19f6
  volumes:
    - haproxy/:/haproxy-override
  links:
    - apiservice:apiservice
    - douitsu:douitsu
    - mqttproxy:mqttproxy
  ports:
    - "80:80"
    - "443:443"
    - "8883:8883"
  expose:
    - "80"
    - "443"
    - "8883:8883"

